-- =============================================================================
-- sec_00_README.sql
-- Security audit script set for PostgreSQL.
--
-- All scripts are READ-ONLY: only SELECT and SHOW. No CREATE, ALTER, DROP,
-- INSERT, UPDATE, DELETE, GRANT, or REVOKE statements anywhere in the set.
-- No temp tables, no functions, no objects of any kind are created.
--
-- Target: PostgreSQL 13+. Some queries reference catalogs added in newer
-- versions (pg_hba_file_rules in 10, pg_ident_file_mappings in 16). They
-- will error on older versions; the rest of each script is unaffected.
--
-- Required privileges: most queries work for any login role. Reading
-- pg_authid (password hashes) requires superuser or pg_read_all_settings.
-- Reading pg_hba_file_rules and pg_ident_file_mappings requires superuser.
-- On AWS RDS use the rds_superuser role for those.
--
-- Recommended execution order — CRITICAL FIRST:
--
--   CRITICAL (run first — access and compromise risks):
--     sec_01_users_and_roles_inventory.sql       Full role inventory
--     sec_02_effective_privileges.sql            Who can access what
--     sec_03_admin_and_superusers.sql            Admin-level accounts
--     sec_04_public_and_excessive_grants.sql     PUBLIC / broad grants
--     sec_05_authentication_and_passwords.sql    Auth methods, weak pwds
--
--   HIGH:
--     sec_06_audit_logging.sql                   Logging & pgaudit status
--     sec_07_encryption_status.sql               SSL/TLS in transit
--     sec_08_network_exposure.sql                Listen addr, pg_hba CIDRs
--     sec_09_sensitive_data_discovery.sql        PII heuristics + RLS
--     sec_10_dangerous_objects.sql               SECURITY DEFINER, FDW, etc
--
--   MEDIUM:
--     sec_11_role_inheritance_chains.sql         Recursive membership graph
--     sec_12_dormant_users.sql                   Inactive accounts
--     sec_13_service_accounts.sql                Technical accounts audit
--     sec_14_backup_security.sql                 Replication / backup access
--     sec_15_external_integrations.sql           FDW, dblink, pub/sub
--
--   LOW (nice to have):
--     sec_16_pii_naming_heuristics.sql           Extended PII patterns
--     sec_17_deprecated_features.sql             md5, untrusted langs, TLSv1
--     sec_18_audit_gaps.sql                      What is NOT being logged
--
-- Notes:
--   * Encryption AT REST is not visible from inside PostgreSQL — verify it
--     at the storage / cloud layer (AWS KMS, LUKS, etc.). Script 07 covers
--     only encryption IN TRANSIT.
--   * "Dormant user" detection (script 12) is approximate — PostgreSQL does
--     not track last successful login natively. Use pgaudit / log analysis
--     for accurate dormancy tracking.
--   * PII discovery (scripts 09 and 16) is heuristic and based on column
--     names. Expect false positives and false negatives. Manual review
--     is required.
--   * pgaudit-specific queries (scripts 06 and 18) return empty results if
--     the extension is not loaded.
-- =============================================================================

SELECT 'See header comment for execution order and requirements.' AS readme;
